### ISSUE TITLE
Delete fork

### ISSUE THREAD

**Issue by ApolloFops** [roboblazers7617/code-standards#4]
I transferred ownership of this repo so the repo settings and issues would be transferred, so the fork at https://github.com/roboblazers7617/Code_Standards can be deleted.

**Comment by fodfodfod** [comment]
Just to confirm, you want me to delete the Code_Standards repository (with capital letters), the one that hasn't been updated in 4 days.

**Comment by ApolloFops** [comment]
@fodfodfod Yes. The repo to delete (`roboblazers7617/Code_Standards`) should show as being forked from this one.

**Comment by fodfodfod** [comment]
The repository has been deleted
